In [1]:
# Summary 

# np diff

# axis (lists vs dfs)


In [ ]:
# np diff

import numpy as np
import pandas as pd

x = np.array([1, 2, 4, 7, 0])

np.diff(x)
# array([ 1,  2,  3, -7])

np.diff(x, n=2)
# 2-1 = 1, 4-2 = 2, 7-4 = 3, 0-7 = -7
# 2-1 = 1, 3-2 = 1, -7-3 = -10
# array([  1,   1, -10])


new_array = np.array([[14, 22, 25, 36], [11, 17, 14, 29]])

new_output=np.diff(new_array, axis=0)
# 11-14 = -3, 17-22 = -5, 14-25 = -11, 29-36 = -7
# [[ -3  -5 -11  -7]]

result = np.diff(new_array, axis=1)
# [[ 8  3 11], [ 6 -3 15]]

# same as:
result = np.diff(new_array)
# [[ 8  3 11], [ 6 -3 15]]


x = np.arange('1066-10-13', '1066-10-16', dtype=np.datetime64)
# array(['1066-10-13', '1066-10-14', '1066-10-15'], dtype='datetime64[D]')

np.diff(x)
# array([1, 1], dtype='timedelta64[D]')



In [ ]:

# axis lists vs dfs

arr = [0, -1, 2, 9, 5, 8]

d = pd.DataFrame(arr)
#    0
# 0  0
# 1 -1
# 2  2
# 3  9
# 4  5
# 5  8

diff_arr_axis0 = np.diff(arr, axis=0)
# array([-1,  3,  7, -4,  3])
diff_df_axis0 = np.diff(d, axis=0)
# array([[-1],
#        [ 3],
#        [ 7],
#        [-4],
#        [ 3]], dtype=int64)


diff_arr_axis1 = np.diff(arr, axis=1)
# numpy.AxisError: axis 1 is out of bounds for array of dimension 1
diff_df_axis1 = np.diff(d, axis=1)
# array([], shape=(6, 0), dtype=int64)


# cuz 
# the (axis = 0) of an array is the rows, and the (axis = 1) of an array is the columns
# and the (axis = 0) of a df is the columns, and the (axis = 1) of a df is the rows