In [1]:
# Summary 

# np diff

# axis (lists vs dfs)


In [ ]:
# np diff


import numpy as np
import pandas as pd

new_array = np.array([[14, 22, 25, 36], [11, 17, 14, 29]])

new_output=np.diff(new_array, axis=0)
# 11-14 = -3, 17-22 = -5, 14-25 = -11, 29-36 = -7
# [[ -3  -5 -11  -7]]

result = np.diff(new_array, axis=1)
# [[ 8  3 11], [ 6 -3 15]]

# same as:
result = np.diff(new_array)
# [[ 8  3 11], [ 6 -3 15]]



x = np.array([1, 2, 4, 7, 0])

np.diff(x)
# array([ 1,  2,  3, -7])

np.diff(x, n=2)
# 2-1 = 1, 4-2 = 2, 7-4 = 3, 0-7 = -7
# 2-1 = 1, 3-2 = 1, -7-3 = -10
# array([  1,   1, -10])


x = np.arange('1066-10-13', '1066-10-16', dtype=np.datetime64)
# array(['1066-10-13', '1066-10-14', '1066-10-15'], dtype='datetime64[D]')

np.diff(x)
# array([1, 1], dtype='timedelta64[D]')



In [ ]:

# axis lists vs dfs

# the default is the last axis, 

# axis =0 is vertical, axis =1 is horizontal. 

lst1 = [0, -1, 2, 9, 5, 8]
lst2 = [[0, -1, 2, 9, 5, 8], [4, -5, 2, 9, 7, 8]]

s = pd.DataFrame(lst1)
#    0
# 0  0
# 1 -1
# 2  2
# 3  9
# 4  5
# 5  8

d = pd.DataFrame(lst2)
#    0  1  2  3  4  5
# 0  0 -1  2  9  5  8
# 1  4 -5  2  9  7  8


# default is axis =0 (lst1)
diff_lst1 = np.diff(lst1)
# array([-1,  3,  7, -4,  3])

diff_lst1_axis0 = np.diff(lst1, axis=0)
# array([-1,  3,  7, -4,  3])

diff_lst1_axis1 = np.diff(lst1, axis=1)
# numpy.AxisError: axis 1 is out of bounds for array of dimension 1


# default is axis =1 (lst2)
diff_lst2 = np.diff(lst2)
# array([[-1,  3,  7, -4,  3],
#        [-9,  7,  7, -2,  1]])

diff_lst2_axis0 = np.diff(lst2, axis=0)
# array([[ 4, -4,  0,  0,  2,  0]])

diff_lst2_axis1 = np.diff(lst2, axis=1)
# array([[-1,  3,  7, -4,  3],
#        [-9,  7,  7, -2,  1]])



# default is axis =1 (cuz s is not a serie it's a df)
diff_s= np.diff(s)
# array([], shape=(6, 0), dtype=int64)

diff_s_axis0 = np.diff(s, axis=0)
# array([[-1],
#        [ 3],
#        [ 7],
#        [-4],
#        [ 3]], dtype=int64)

diff_s_axis1 = np.diff(s, axis=1)
# array([], shape=(6, 0), dtype=int64)



# default is axis =1 (d)
diff_d= np.diff(d)
# array([[-1,  3,  7, -4,  3],
#        [-9,  7,  7, -2,  1]], dtype=int64)

diff_d_axis0 = np.diff(d, axis=0)
# array([[ 4, -4,  0,  0,  2,  0]], dtype=int64)

diff_d_axis1 = np.diff(d, axis=1)
# array([[-1,  3,  7, -4,  3],
#        [-9,  7,  7, -2,  1]], dtype=int64)


# remember:
# pd.DataFrame gives you a df, even if its only one column
#  a serie has one axis, a df has two axes.

#  a one line array has one axis, a multi line array has two axes.

# if you took a column from a df, you get a serie.
# for example: a df has 3 comlumns a, b and c . 
# type(df) is a df but type(df['b]) is a serie.

# list default behavior is horizontal
# df/serie default behavior is vertical 
# default axis is the last axis.